## Tensors: creation,dtype,device,basic ops

In [1]:
import torch

In [4]:
a=torch.tensor([[1,2],[2,5]])
b=torch.tensor([1.0,2.0])

print("a",a)
print("b",b)

a tensor([[1, 2],
        [2, 5]])
b tensor([1., 2.])


In [5]:
import numpy as np
arr=np.array([1,2])
arr_tensor=torch.tensor(arr)

print(arr)
print(arr_tensor)

[1 2]
tensor([1, 2])


In [8]:
print("size:",a.size())

size: torch.Size([2, 2])


In [9]:
print("data type:",a.dtype)

data type: torch.int64


In [10]:
print("data type:",b.dtype)

data type: torch.float32


In [11]:
print("device:",a.device)

device: cpu


In [12]:
print("Is GPU available:",torch.cuda.is_available())

Is GPU available: True


In [13]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [14]:
device

'cuda'

In [15]:
a=a.to(device)
print(a)

tensor([[1, 2],
        [2, 5]], device='cuda:0')


In [16]:
print(a.device)

cuda:0


In [17]:
b=b.to(device)
c=a+b
print(c)

tensor([[2., 4.],
        [3., 7.]], device='cuda:0')


In [18]:
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([10,20])

c=a+b
print("c:",c)

c: tensor([[11, 22],
        [13, 24]])


In [19]:
dir(a)

['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_c_exchange_api__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__'

## Image tensor format [B,C,H,W] and reshaping

In [25]:
#B= Batch Size
#C= Channels
#H= Height of image
#W= Width of image

a=torch.randn(8,3,256,256)

b=a.reshape(8,3,256*256)

c=a.permute(0,3,2,1)

print("size of a",a.size())
print("size of b",b.size())
print("size of c",c.size())

size of a torch.Size([8, 3, 256, 256])
size of b torch.Size([8, 3, 65536])
size of c torch.Size([8, 256, 256, 3])


## Autograd computational graph, .backward(), .grad, .no_grad, detach()

In [28]:
a=torch.tensor(2.0, requires_grad=True)
b=torch.tensor(3.0, requires_grad=True)

z=a**2 + b*3
out=2.0*z

out.backward()
print("out:",out)

out: tensor(26., grad_fn=<MulBackward0>)


In [29]:
print(a.grad)
print(b.grad)

tensor(8.)
tensor(6.)


In [30]:
z=a**2 + b*3
out=2.0*z

out.backward()
print("out:",out)
print(a.grad)
print(b.grad)

out: tensor(26., grad_fn=<MulBackward0>)
tensor(16.)
tensor(12.)


In [31]:
with torch.no_grad():
    pred=a**2+3*b
    print(pred)

tensor(13.)


## nn.Module,layers(Linear,Covo2d), and feature maps

In [32]:
import torch.nn as nn

In [35]:
conv= nn.Conv2d(in_channels=3,out_channels=64,kernel_size=3,padding=1)
x=torch.randn(8,3,256,256)
out=conv(x)
print("input shape:",x.size())
print("output shape:",out.size())

input shape: torch.Size([8, 3, 256, 256])
output shape: torch.Size([8, 64, 256, 256])


In [40]:
class CNNNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.net=nn.Sequential(
            nn.Conv2d(3,16,3,padding=1),
            nn.ReLU(),
            nn.Conv2d(16,8,3,padding=1),
            nn.ReLU(),
            nn.Flatten(),
            nn.Linear(8*256*256,10)
        )

    def forward(self,x):
        return self.net(x)

In [41]:
model=CNNNet()
print(model)

CNNNet(
  (net): Sequential(
    (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
    (2): Conv2d(16, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU()
    (4): Flatten(start_dim=1, end_dim=-1)
    (5): Linear(in_features=524288, out_features=10, bias=True)
  )
)


In [42]:
x=torch.randn(8,3,256,256)
out=model(x)

In [43]:
print(out)

tensor([[-3.2723e-02, -2.3120e-02,  5.5742e-02,  1.5051e-04,  1.4296e-01,
         -4.3691e-02,  1.7817e-01, -1.2070e-01, -1.2345e-02,  7.1635e-02],
        [-4.5272e-02,  6.2183e-02, -1.1905e-01, -2.9400e-02,  1.7961e-01,
          8.8306e-02,  1.5794e-01, -1.5387e-02, -7.4868e-02,  4.6473e-03],
        [-6.6747e-02, -7.1320e-03, -2.3646e-04, -9.8756e-02,  2.9466e-01,
          5.2110e-02,  1.0823e-01, -7.3133e-02, -1.5335e-02,  1.0515e-01],
        [-1.0828e-01, -3.1910e-02, -6.2066e-02, -8.2298e-02,  6.3143e-02,
          1.3359e-01,  1.6361e-02, -1.5618e-01, -1.3318e-02,  1.0861e-01],
        [-5.0990e-02,  3.5707e-02, -1.7739e-01,  5.0836e-02,  4.3829e-02,
          1.8262e-02,  2.6398e-01, -4.4959e-02,  1.3168e-01, -1.8026e-02],
        [ 4.0098e-02, -6.4397e-02, -8.2105e-02, -5.1000e-02,  3.7494e-02,
         -1.5758e-02,  1.4103e-01, -1.5109e-01, -1.5836e-01,  1.2274e-01],
        [ 7.9106e-02,  1.2843e-02, -4.2399e-02, -4.6955e-02,  6.2828e-02,
         -6.2845e-02,  1.7658e-0

In [45]:
print(out.size())

torch.Size([8, 10])


## Optimizers

In [46]:
import torch.optim as optim

In [47]:
dir(optim)

['ASGD',
 'Adadelta',
 'Adafactor',
 'Adagrad',
 'Adam',
 'AdamW',
 'Adamax',
 'LBFGS',
 'Muon',
 'NAdam',
 'Optimizer',
 'RAdam',
 'RMSprop',
 'Rprop',
 'SGD',
 'SparseAdam',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_adafactor',
 '_functional',
 '_muon',
 'lr_scheduler',
 'swa_utils']

In [48]:
optimizer=optim.Adam(model.parameters())
optimizer.step()